background {
    monitor =
    path = /home/smoo/Pictures/Wallpapers/snow.png
    blur_passes = 2
    blur_size = 4
}

input-field {
    monitor =
    size = 280, 48
    outline_thickness = 1
    dots_size = 0.22
    dots_spacing = 0.18
    fade_on_empty = false
    placeholder_text = Password
    hide_input = false
    rounding = 4
    outer_color = rgb(A5B5AB)
    inner_color = rgba(13, 15, 16, 0.80)
    font_color = rgb(F8EBE3)
    check_color = rgb(A5B5AB)
    fail_color = rgb(F0334A)
    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgb(F8EBE3)
    font_size = 48
    font_family = JetBrainsMono Nerd Font
    position = 0, 70
    halign = center
    valign = center
}
